language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
  - pip install pep8 . --use-mirrors
script:
  - nosetests
  - pep8 --ignore=W bipy setup.py
