# Check on http://lint.travis-ci.org/ after modifying it!  Originally
# modified from https://gist.github.com/dan-blanchard/7045057
language: python
env:
  - PYTHON_VERSION=3.4 NUMPY_VERSION=1.8
  - PYTHON_VERSION=2.7 NUMPY_VERSION=1.8 WITH_DOCTEST=True
  - PYTHON_VERSION=2.7 NUMPY_VERSION=1.7
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION pip numpy=$NUMPY_VERSION scipy matplotlib nose pep8 Sphinx
  - source activate env_name
  - pip install sphinx-bootstrap-theme future
  - pip install . --no-deps
script:
  - if [ ${WITH_DOCTEST} ]; then nosetests --with-doctest; else nosetests; fi
  - pep8 skbio setup.py
  - pushd doc
  - make clean
  - make html
  # linkcheck disabled in Py3 (bug in Sphinx)
  - if [ $PYTHON_VERSION ==  2.7 ]; then make linkcheck; fi
  - popd
